SELECT D.DNAME, E.LNAME, E.FNAME, P.PNAME FROM DEPARTMENT AS D, EMPLOYEE AS E, WORKS_ON AS W, PROJECT AS P
WHERE D.DNUMBER = E.DNO AND E.SSN = W.ESSN AND W.PNO = P.PNUMBER ORDER BY D.DNAME, E.LNAME, E.FNAME;

SELECT FNAME, LNAME FROM EMPLOYEE WHERE DNO = 5 AND 
SSN IN (SELECT W.ESSN FROM WORKS_ON AS W WHERE W.HOURS > 10 AND 
W.PNO = (SELECT P.PNUMBER FROM PROJECT AS P WHERE P.PNAME = 'ProductX'));

SELECT E.FNAME, E.LNAME FROM EMPLOYEE AS E
WHERE E.SSN IN (SELECT ESSN FROM DEPENDENT WHERE E.FNAME = DEPENDENT_NAME);

SELECT * INTO EMPLOYEE_BACKUP FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE SUPER_SSN IS NULL;

SELECT E.FNAME, E.LNAME FROM EMPLOYEE AS E
WHERE E.SSN IN (SELECT ESSN FROM DEPENDENT WHERE E.FNAME = DEPENDENT_NAME AND E.SEX = SEX);

SELECT PNUMBER, PNAME, COUNT (*)
FROM PROJECT, WORKS_ON
WHERE PNUMBER = PNO AND ESSN IN (SELECT E.SSN FROM EMPLOYEE AS E WHERE E.DNO = 5)
GROUP BY PNUMBER, PNAME;

SELECT DNAME, COUNT(*) FROM DEPARTMENT, EMPLOYEE 
WHERE DNUMBER = DNO AND SALARY>40000 AND 
DNO IN (SELECT DNO FROM EMPLOYEE GROUP BY DNO HAVING COUNT(*)>5) 
GROUP BY DNAME;

SELECT FNAME, LNAME FROM EMPLOYEE WHERE SALARY >= (SELECT MIN(SALARY) FROM EMPLOYEE)+10000;

SELECT FNAME,LNAME FROM EMPLOYEE WHERE SSN='%7900%';

SELECT FNAME, LNAME, DNO FROM EMPLOYEE WHERE DNO=5 OR DNO=1 ORDER BY FNAME;