SELECT * FROM EMPLOYEE WHERE SSN NOT IN (SELECT ESSN FROM DEPENDENT);



SELECT P.PNUMBER, P.DNUM, E.LNAME, E.ADDRESS, E.BDATE FROM PROJECT AS P, DEPARTMENT AS D, EMPLOYEE AS E 
WHERE P.PLOCATION = 'Stafford' AND P.DNUM = D.DNUMBER AND D.MGR_SSN = E.SSN;

(SELECT W.PNO FROM WORKS_ON AS W, EMPLOYEE AS E WHERE E.LNAME = 'Smith' AND E.SSN = W.ESSN)
UNION
(SELECT W.PNO FROM WORKS_ON AS W, PROJECT AS P, EMPLOYEE AS E, DEPARTMENT AS D 
WHERE E.LNAME = 'Smith' AND W.PNO = P.PNUMBER AND P.DNUM = D.DNUMBER AND D.MGR_SSN = E.SSN);

SELECT DISTINCT(E.FNAME) FROM EMPLOYEE AS E, WORKS_ON AS W, PROJECT AS P 
WHERE P.PNAME = 'ProductX' AND P.PNUMBER = W.PNO AND W.HOURS > 10 AND W.ESSN = E.SSN AND E.DNO = 5;

SELECT E.FNAME FROM EMPLOYEE AS E, DEPENDENT AS D WHERE E.FNAME = D.DEPENDENT_NAME AND E.SSN = D.ESSN;

SELECT E.FNAME, E.LNAME, P.PNAME FROM EMPLOYEE AS E, DEPARTMENT AS D, WORKS_ON AS W, PROJECT AS P 
WHERE W.ESSN = E.SSN AND W.PNO = P.PNUMBER AND P.DNUM = D.DNUMBER
ORDER BY D.DNAME, E.LNAME, E.FNAME;

SELECT E.SALARY*1.15 FROM PROJECT AS P, WORKS_ON AS W, EMPLOYEE AS E 
WHERE P.PNAME = 'ProductX' AND P.PNUMBER = W.PNO and W.ESSN = E.SSN;