SELECT SUM(SALARY), MIN(SALARY), MAX(SALARY), AVG(SALARY) FROM EMPLOYEE;

SELECT SUM(SALARY), MIN(SALARY), MAX(SALARY), AVG(SALARY) FROM EMPLOYEE WHERE DNO = (SELECT DNUMBER FROM DEPARTMENT WHERE DNAME = 'Research');

SELECT COUNT(*) FROM EMPLOYEE;

SELECT COUNT(*) FROM EMPLOYEE WHERE DNO = (SELECT DNUMBER FROM DEPARTMENT WHERE DNAME = 'Research');

SELECT COUNT(DISTINCT SALARY) FROM EMPLOYEE;

SELECT FNAME, LNAME FROM EMPLOYEE WHERE(SELECT COUNT(*) FROM DEPENDENT WHERE SSN=ESSN)>=2;

SELECT DNO, COUNT(*), AVG(SALARY) FROM EMPLOYEE GROUP BY DNO;

SELECT PNUMBER, PNAME, COUNT(*) FROM PROJECT, WORKS_ON WHERE PNUMBER = PNO GROUP BY PNUMBER, PNAME;

SELECT P.PNUMBER, P.PNAME, COUNT(W.PNO) FROM PROJECT AS P, WORKS_ON AS W
WHERE P.PNUMBER = W.PNO GROUP BY P.PNUMBER, P.PNAME, W.PNO HAVING COUNT(W.PNO)>2;

SELECT FNAME, LNAME FROM EMPLOYEE, DEPARTMENT WHERE SSN = MGR_SSN AND (SELECT COUNT(*) FROM DEPENDENT WHERE SSN=ESSN)>=1;

SELECT DISTINCT SALARY FROM EMPLOYEE;

SELECT FNAME, REPLICATE('*',SALARY/100) FROM EMPLOYEE; 

SELECT COUNT(DISTINCT MGR_SSN) FROM DEPARTMENT;

SELECT D.DNAME, LOC.DLOCATION, COUNT(E.DNO), AVG(E.SALARY) FROM DEPARTMENT AS D, EMPLOYEE AS E, DEPT_LOCATIONS AS LOC 
WHERE D.DNUMBER = E.DNO AND D.DNUMBER = LOC.DNUMBER GROUP BY D.DNAME, LOC.DLOCATION, E.DNO;

SELECT SSN, FNAME, LNAME FROM EMPLOYEE WHERE SALARY> (SELECT AVG(SALARY) FROM EMPLOYEE);