CREATE VIEW WORKS_ON1 AS
SELECT E.FNAME AS FNAME, E.LNAME AS LNAME, P.PNAME AS PNAME, W.HOURS AS HOURS
FROM EMPLOYEE E, PROJECT P, WORKS_ON W
WHERE E.SSN = W.ESSN AND P.PNUMBER = W.PNO;

CREATE VIEW DEPT_INFO AS
SELECT DNAME, COUNT(*) EMP_COUNT, SUM(SALARY) AS SALARY 
FROM DEPARTMENT, EMPLOYEE WHERE DNO = DNUMBER GROUP BY DNAME;

SELECT * FROM WORKS_ON1;
UPDATE WORKS_ON1 SET PNAME = 'ProductY' WHERE FNAME = 'John' AND PNAME = 'ProductX';

DROP VIEW WORKS_ON1;

CREATE VIEW DEPT AS
SELECT D.DNAME AS DNAME, E.FNAME AS FNAME, E.LNAME AS LNAME, E.SALARY AS SALARY
FROM EMPLOYEE E, DEPARTMENT D WHERE E.SSN = D.MGR_SSN;

SELECT * FROM DEPT;
DROP VIEW DEPT;

CREATE VIEW RESEARCH AS
SELECT E1.FNAME AS FNAME, E2.FNAME AS SFNAME, E1.SALARY AS SALARY
FROM EMPLOYEE E1,EMPLOYEE E2, DEPARTMENT D
WHERE E1.SUPER_SSN = E2.SSN AND E1.DNO = (SELECT D.DNUMBER WHERE DNAME = 'Research');

SELECT * FROM RESEARCH
DROP VIEW RESEARCH

CREATE VIEW PROJ AS 
SELECT PNAME AS PROJECT, DNAME AS DEPT, 
(SELECT COUNT(*) FROM WORKS_ON W WHERE W.PNO = P.PNUMBER) AS EMPLOYEES, 
(SELECT SUM(W.Hours) FROM WORKS_ON W WHERE W.PNO = P.PNUMBER GROUP BY PNO) AS HOURS 
FROM PROJECT P, DEPARTMENT D WHERE P.DNUM = D.DNUMBER;

SELECT * FROM PROJ
DROP VIEW PROJ

CREATE VIEW NEW_PROJ AS
SELECT PNAME AS PROJECT, DNAME AS DEPT, 
(SELECT COUNT(*) FROM WORKS_ON W WHERE W.PNO = P.PNUMBER) AS EMPLOYEES, 
(SELECT SUM(W.Hours) FROM WORKS_ON W WHERE W.PNO = P.PNUMBER GROUP BY PNO) AS HOURS
FROM PROJECT P, DEPARTMENT D 
WHERE P.DNUM = D.DNUMBER AND (SELECT COUNT(*) FROM WORKS_ON W WHERE W.PNO = P.PNUMBER GROUP BY W.PNO)>1;

SELECT * FROM PROJ
DROP VIEW PROJ

CREATE VIEW DEPT5 AS
SELECT * FROM EMPLOYEE WHERE DNO = 5;

SELECT * FROM DEPT5
DROP VIEW DEPT5

SELECT * FROM EMPLOYEE;
ALTER TABLE EMPLOYEE
DROP COLUMN ADDRESS;
SELECT * FROM EMPLOYEE;