SELECT DNAME, COUNT(*) NO_OF_EMPLOYEE FROM DEPARTMENT, EMPLOYEE WHERE DNO = DNUMBER GROUP BY DNAME HAVING AVG(SALARY)>30000;

SELECT FNAME FROM EMPLOYEE
WHERE DNO = (SELECT DNO FROM EMPLOYEE WHERE SALARY = (SELECT Max(SALARY) FROM EMPLOYEE));

SELECT E1.FNAME FROM EMPLOYEE AS E1, EMPLOYEE AS E2 WHERE E1.SUPER_SSN = E2.SSN AND E2.SUPER_SSN = 888665555;

SELECT FNAME FROM EMPLOYEE WHERE SUPER_SSN IS NULL;

SELECT E.FNAME, E.LNAME, (SELECT DATEDIFF(YEAR,E.BDATE,GETDATE()) + 0) AS AGE, D.DNAME, D.DNUMBER 
FROM EMPLOYEE AS E, DEPARTMENT AS D WHERE D.DNUMBER = E.DNO;

SELECT E1.FNAME AS ENAME, E1.SSN AS ESSN, E2.FNAME AS MNAME, E2.SSN AS MSSN 
FROM EMPLOYEE AS E1 LEFT OUTER JOIN EMPLOYEE AS E2 ON E1.SUPER_SSN = E2.SSN;

SELECT CONCAT(FNAME,' earns ',SALARY,' monthly but wants ',3*SALARY) AS DREAM_SALARY FROM EMPLOYEE;