SELECT CONCAT(UPPER(SUBSTRING(FNAME,1,1)),LOWER(SUBSTRING(FNAME,2,14))) AS NAME, LEN(FNAME) FROM EMPLOYEE 
WHERE (FNAME LIKE 'J%' OR FNAME LIKE 'A%' OR FNAME LIKE 'M%');

SELECT E.SSN, D.DNAME FROM EMPLOYEE AS E, DEPARTMENT AS D WHERE E.DNO = D.DNUMBER;

SELECT FNAME, LNAME, SALARY FROM EMPLOYEE WHERE SALARY > 25000;

SELECT E.FNAME, E.LNAME, E.ADDRESS FROM EMPLOYEE AS E, DEPARTMENT AS D WHERE E.DNO = D.DNUMBER AND D.DNAME = 'Research';

(SELECT DISTINCT PNUMBER FROM PROJECT, DEPARTMENT, EMPLOYEE
WHERE DNUM = DNUMBER AND MGR_SSN = SSN AND LNAME = 'Smith') 
UNION 
(SELECT DISTINCT PNUMBER FROM PROJECT, WORKS_ON, EMPLOYEE
WHERE PNUMBER = PNO AND ESSN = SSN AND LNAME = 'Smith');

SELECT * FROM EMPLOYEE WHERE ADDRESS LIKE '%Housten, TX%';

SELECT * FROM EMPLOYEE WHERE BDATE >= '1950-01-01' AND BDATE < '1960-01-01';

SELECT E.SALARY*1.1 FROM EMPLOYEE AS E, PROJECT AS P,WORKS_ON AS W WHERE P.PNAME = 'ProductX' AND W.PNO = P.PNUMBER AND W.ESSN = E.SSN;

SELECT * FROM EMPLOYEE WHERE DNO = 5 AND SALARY >= 30000 AND SALARY <= 40000;

SELECT E1.FNAME, E1.LNAME FROM EMPLOYEE AS E1, EMPLOYEE AS E2 WHERE E1.SUPER_SSN = E2.SSN AND E2.FNAME = 'Franklin' AND E2.LNAME = 'Wong';