SELECT * FROM DEPARTMENT
SELECT * FROM DEPENDENT
SELECT * FROM DEPT_LOCATIONS
SELECT * FROM EMPLOYEE
SELECT * FROM PROJECT
SELECT * FROM WORKS_ON

SELECT SSN FROM EMPLOYEE;

SELECT FNAME, LNAME, SSN FROM EMPLOYEE WHERE DNO = 5;

SELECT BDATE, ADDRESS FROM EMPLOYEE WHERE FNAME = 'John' AND MINIT = 'B' AND LNAME = 'Smith';

SELECT P.PNUMBER, P.DNUM, E.LNAME, E.ADDRESS, E.BDATE 
FROM PROJECT P, DEPARTMENT D, EMPLOYEE E
WHERE P.PLOCATION = 'Stafford' AND P.DNUM = D.DNUMBER AND D.MGR_SSN = E.SSN;

SELECT CONCAT(FNAME, ', ', MINIT, ',', LNAME, ', ', SSN, ',' ,BDATE, ',' , ADDRESS, ',' , SEX, ',' , SALARY, ',' , SALARY, ',' , SUPER_SSN, ',' , DNO) AS THE_OUTPUT FROM EMPLOYEE;

SELECT E.FNAME, E.LNAME, S.FNAME, S.LNAME FROM EMPLOYEE as E, EMPLOYEE as S WHERE E.SUPER_SSN=S.SSN;

SELECT FNAME FROM EMPLOYEE WHERE FNAME LIKE '__A%';

SELECT FNAME FROM EMPLOYEE WHERE (FNAME LIKE '%A%A%' OR FNAME LIKE '%R%R%') AND (DNO = 5 OR SUPER_SSN = 123456789);

SELECT GETDATE() AS PRESENT;

SELECT SALARY from EMPLOYEE;