UPDATE EMPLOYEE SET SALARY = SALARY*1.5
WHERE SSN IN (SELECT MGR_SSN FROM DEPARTMENT);

UPDATE EMPLOYEE SET SALARY = SALARY*0.9
WHERE SSN IN (SELECT MGR_SSN FROM DEPARTMENT WHERE DNUMBER = (SELECT DNUM FROM PROJECT WHERE PNUMBER = 10));

UPDATE PROJECT SET PNAME = 'XYZ' WHERE DNUM = 5;

DELETE FROM DEPENDENT WHERE ESSN = 123456789;

UPDATE DEPT_LOCATIONS SET DLOCATION = 'New York' 
WHERE DNUMBER = (SELECT D.DNUMBER FROM DEPARTMENT D WHERE D.DNAME = 'Research');

UPDATE EMPLOYEE SET SALARY = 2*SALARY 
WHERE SSN IN (SELECT ESSN FROM WORKS_ON WHERE PNO = (SELECT PNUMBER FROM PROJECT WHERE PNAME = 'ProductX'));

UPDATE EMPLOYEE SET SUPER_SSN = 987654321 WHERE SUPER_SSN = 333445555;

DELETE FROM EMPLOYEE WHERE (SELECT DATEDIFF(YEAR,BDATE,GETDATE()) + 0)>65;

ALTER TABLE DEPARTMENT ADD DEFAULT 333445555 FOR MGR_SSN;
DROP DEFAULT IF EXISTS MGR_SSN;